### ISSUE TITLE
结束休眠后，圆角部分显示错位

### ISSUE THREAD

**Issue by Anivie** [RoundedCorners/Application#202]
In Windows 11, after the computer wakes up from sleep mode, the rounded corners appear in the middle of the screen instead of the edges.
My computer has two screens, one with 1080p resolution and the other with 2K resolution, this program runs normally at system startup, hope this information helps you identify the problem.

**Comment by NikolaRHristov** [comment]
在上面。

**Comment by Anivie** [comment]
> 在上面。

Apologize for not realizing that you don't speak Chinese. I have translated my question into English, hoping that it can be of help to you.
